name: Format

on:
  pull_request:
    branches: ['main']
    types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "black[jupyter]"
    - name: Check formating with black
      run: |
        black algorithms qbraid_lab qbraid_sdk qbraid_qir --line-length=100 --check